<?xml version = "1.0"?>
<!DOCTYPE codelean [
        <!ELEMENT codelean (to, from, subject, message)>
        <!ELEMENT to (#PCDATA)>
        <!ELEMENT from (#PCDATA)>
        <!ELEMENT subject (#PCDATA)>
        <!ELEMENT message (#PCDATA)>
        ]>
<codelean>
    <to>My Reader</to>
    <from>ThiDK</from>
    <subject>A Message to my readers</subject>
    <message>Welcome to codelearn.vn</message>
</codelean>